stages: 
    - build
    - package
    - test
    - deploy
    # - test
    # - deploy staging
    # - deploy production

variables:
    APP_VERSION: $CI_PIPELINE_IID

build website:
    image: node:16-alpine
    stage: build
    script:
        - yarn install
        - yarn lint
        - yarn test 
        - yarn build
        - echo $APP_VERSION > build/version.html
    artifacts:
        paths:
            - build

.build docker image:
    stage: package
    image: docker:20.10.12
    services:
        - docker:20.10.12-dind
    script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - docker build -t $CI_REGISTRY_IMAGE -t $CI_REGISTRY_IMAGE:$APP_VERSION .
        - docker image ls
        - docker push --all-tags $CI_REGISTRY_IMAGE

.test docker image:
    stage: test 
    image: curlimages/curl
    services:
        - name: $CI_REGISTRY_IMAGE:$APP_VERSION
          alias: website
    script:
        - curl http://website/version.html | grep $APP_VERSION

deploy to production:
    image:
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    stage: deploy
    environment: production
    script:
        - aws --version 
        - yum install -y gettext
        - export DEPLOY_TOKEN=$(echo $GITLAB_DEPLOY_TOKEN | td -d "\n" | base64)
        - envsubst < template/Dockerrun.aws.json > Dockerrun.aws.json
        - envsubst < template/auth.json > auth.json
        - cat Dockerrun.aws.json
        - cat auth.json
        - aws s3 cp Dockerrun.aws.json s3://$AWS_S3_BUCKET/Dockerrun.aws.json 
        - aws s3 cp auth.json s3://$AWS_S3_BUCKET/auth.json

# test website:
#     image: node:16-alpine
#     stage: test 
#     script:
#         - yarn global add serve 
#         - apk add curl
#         - serve -s build &
#         - sleep 10
#         - curl http://localhost:3000 | grep "React App"

# .deploy:
#     image: 
#         name: amazon/aws-cli:2.4.11
#         entrypoint: [""]
#     rules:
#         - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
#     script: 
#         - aws --version
#         - echo $CI_COMMIT_REF_NAME
#         - aws s3 sync build s3://$AWS_S3_BUCKET --delete
#         - curl $CI_ENVIRONMENT_URL | grep "React App"
#         - curl $CI_ENVIRONMENT_URL/version.html | grep $APP_VERSION

# deploy to staging:
#     stage: deploy staging
#     environment: staging
#     extends: .deploy

# deploy to production:
#     stage: deploy production
#     when: manual
#     environment: production
#     extends: .deploy
