stages: 
    - build
    - test
    - deploy
    - post deploy

variables:
    APP_BASE_URL: http://gitlabs-20220606.s3-website.ap-northeast-2.amazonaws.com

build website:
    image: node:16-alpine
    stage: build
    script:
        - yarn install
        - yarn lint
        - yarn test 
        - yarn build
    artifacts:
        paths:
            - build

test website:
    image: node:16-alpine
    stage: test 
    script:
        - yarn global add serve 
        - apk add curl
        - serve -s build &
        - sleep 10
        - curl http://localhost:3000 | grep "React App"

deploy to s3:
    stage: deploy
    image: 
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script: 
        - aws --version
        - echo $CI_COMMIT_REF_NAME
        - aws s3 sync build s3://$AWS_S3_BUCKET --delete

production test:
    stage: post deploy
    image: curlimages/curl
    rules:
        - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    script:
        - curl $APP_BASE_URL | grep "React App"
